config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  resources :items, only: [ :new, :create, :show, :update, :edit ]

  get 'search', to: 'pages#search', as: :search
  resources :brands, only: [ :index ]

  resources :reviews, only: [ :new, :create ]

  resources :users, only: [ :new, :create]

  get 'thank', to: 'pages#thank', as: :thank
  get 'registered', to: 'pages#registered', as: :registered
  get 'unevaluated', to: 'pages#unevaluated', as: :unevaluated

  # For the form with OCR
  get 'items/scan/new', to: 'items#scan_new', as: :scan_new_item
  post 'items/scan', to: 'items#scan_create', as: :scan_items
  get  'items/scan/:id/edit', to: 'items#scan_edit', as: :scan_edit_item
  patch  'items/scan/:id', to: 'items#scan_update', as: :scan

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/_navbar_variation_one.html.erb
<!-- Expect mobile -->
<div class="navbar-wagon hidden-xs hidden-sm">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
    <p class="clothparency-nav">CLOTHPARENCY</p>
  <% end %>

  <div class="navbar-wagon-right hidden-xs hidden-sm">
      <a class="navbar-wagon-item navbar-wagon-link" id="btn-rounded" href="/reviews/new">
        <i class="fa fa-edit"></i> Give your feedbacks
      </a>
  </div>
</div>

<!-- Mobile only -->
<%= link_to root_path, class: "navbar-wagon-brand hidden-md hidden-lg" do %>
  <i class="fa fa-chevron-left chevron-left"></i>
<% end %>
<div class="navbar-wagon hidden-md hidden-lg">
  <!-- Back -->
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
    <p class="clothparency-nav">CLOTHPARENCY</p>
  <% end %>

  <div class="navbar-wagon-right hidden-xs hidden-sm">
      <a class="navbar-wagon-item navbar-wagon-link" id="btn-rounded" href="/reviews/new">
        <i class="fa fa-edit"></i> Give your feedbacks
      </a>
  </div>
</div>

app/views/pages/home.html.erb
<% content_for :navbar do %>
      <%= render 'navbar_variation_one' %>
 <% end %>

<div class="container fixed-page-size">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3 center">
      <h2 class="font-size-home">
        Make informed decisions :
        <br>
        Buy ethically !
      </h2>
      <p class="present-home">Clothparency enables you to change the way you shop, knowing what your really buy.</p>

      <%= image_tag "tshirt-question.png", height: 200, class: "big-icon home-icon" %>
      <%= link_to new_item_path, class: "btn btn-primary btn-full-width fixed-bottom-xs fixed-bottom-sm" do %>
        <i class="fa fa-search dropdown-toggle" data-toggle="dropdown"></i> Specific item score
      <% end %>

      <%= link_to search_path, class: "btn btn-primary btn-full-width fixed-bottom-xs fixed-bottom-sm btn-margin" do %>
        <i class="fa fa-search dropdown-toggle" data-toggle="dropdown"></i> Brand information
      <% end %>
    </div>
  </div>
</div>

app/views/pages/registered.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>C'est noté !</h1>
      <p>
        Nous prenons ta demande en considération et l'intègrons pour la suite.
        <br>
        <br>
        C'est grâce à vos retours que nous pouvons nous améliorer et mieux vous aider à choisir vos vêtements !
        <br>
        <br>
        N'hésite pas à partager l'app à tes amis !
      </p>
      <div class="fb-share-button" data-href="https://app.clothparency.com" data-layout="button_count" data-size="large" data-mobile-iframe="true"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Partager Clothparency</a></div>
      <%= link_to root_path, class: "back-home" do %>
        <i class="fa fa-arrow-left"></i> Retour à l'Accueil
      <% end %>
    </div>
  </div>
</div>

app/views/pages/search.html.erb
<% content_for :navbar do %>
      <%= render 'navbar_variation_one' %>
 <% end %>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3 center">
      <div class="form-item">
        <h1 class="page-title">Look for a brand</h1>

        <form action="/brands" class="form-stuff">
          <div id="brand-names"><p><%= brand_names = Brand.all.map { | brand | brand.name } %></p></div>
          <div class="form-group autocomplete flexbox-center">
            <input name="brand" class="fvalue-input form-control required" type="text" placeholder="Brand *" id="item_brand">
          </div>
          <input type="submit" class="btn-submit btn btn-primary" value="Go !"></input>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/pages/thank.html.erb
<% content_for :navbar do %>
      <%= render 'navbar_variation_one' %>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>Thank you !!!</h1>
      <p>
        Thanks to yours feedbacks, we can improve and guide customers towards more judicious, more ethical and environmentally friendly choices.
        <br>
        <br>
        Don't hesitate to share the app with your relatives !
      </p>
      <div class="fb-share-button" data-href="https://app.clothparency.com" data-layout="button_count" data-size="large" data-mobile-iframe="true"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Partager Clothparency</a></div>
      <%= link_to root_path, class: "back-home" do %>
        <i class="fa fa-arrow-left"></i> Back to Home page
      <% end %>
    </div>
  </div>
</div>

app/views/pages/unevaluated.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>A venir ...</h1>
      <p>
        Cette marque n'a pas encore été évaluée. Nous prenons ta demande en considération et l'intègrons pour la suite.
        <br>
        <br>
        C'est grâce à vos retours que nous pouvons nous améliorer et mieux vous aider à choisir vos vêtements !
        <br>
        <br>
        N'hésite pas à partager l'app à tes amis !
      </p>
      <div class="fb-share-button" data-href="https://app.clothparency.com" data-layout="button_count" data-size="large" data-mobile-iframe="true"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Partager Clothparency</a></div>
      <%= link_to root_path, class: "back-home" do %>
        <i class="fa fa-arrow-left"></i> Retour à l'Accueil
      <% end %>
    </div>
  </div>
</div>